### ISSUE TITLE
UI Design Ideas

### ISSUE THREAD

**Issue by pixeldesu** [surfbirdapp/surfbird#21]
Surfbird currently looks like TweetDeck, which is done on purpose, as the column-based layout itself is pretty good for Twitter clients.

What I want to change is the general style direction, so it does not look like TweetDeck anymore, but as I'm more working on the code side of things, having other people to help me figure out stuff together is more efficient than me switching between code and design constantly!

So, if you have any ideas/feedback, throw them in here, anything is appreciated!

**Comment by tmprnc** [comment]
Hey! You know I would get involved, didn't you?
In fact, I think the idea of it "looking like TweetDeck" is a bit wrong. Sure, your design currently looks very similar, however the column browsing is something that is associated with many Twitter clients and not just TweetDeck. You kind of already said that, but I think there's virtually nothing you can do so that it doesn't look like TweetDeck in a way. Those that don't have multiple columns are generally slow and non-intuitive. The web Twitter app is generally the least preferable one, considering most of the Android clients (including the default Twitter one now) have at least two columns which can be swiped back and forth. Now, on a desktop, you can fit multiple columns on one screen so it's preferable to do so.
Why TweetDeck works so well is specifically because it has the best design idea if not the only valid one in this field.

I would focus design on removing the most bloat possible. Something like a "mobile" theme that emulates the design of the Android/iPhone app would be a start. Of course, a native TweetDeck look-alike would be a good theme for people to start. Of course, I suppose I don't need to introduce you to [snwflk](https://a.pomf.cat/dadnub.png), because I've already shamelessly advertised it quite a lot. I do probably intend to port it as a Surfbird theme but I'm also a lazy piece of shit, so who knows.

Something you can try is a very Material theme like ModernDeck, though I feel its UI is bloated with stuff that's too large and takes too much space, and poorly optimized animations that are quite bad on the RAM. Otherwise, it has okay design ideas. One thing I specifically loathe, however, is displaying the tweet actions buttons (reply, favorite, RT and all that stuff) always on, even when the tweet's not being hovered. Perhaps looking into Materialize.css and the Material guidelines would be a good thing to start.

An iOS theme, maybe? The iOS design language has no specific or public guidelines, but it's mostly [about lots of white, muted "frosted glass" (read: blurry semi-transparent) backgrounds](https://9to5mac.files.wordpress.com/2015/04/img_0673.png?w=496&h=882&crop=1), contrasting light black font and thin icons.
I think the thin icons is an important design element. New Metro/Modern [uses it particularly well](https://a.pomf.cat/tobbcd.png) and this is perhaps the only feature I'd save from Tweeten. God, I hate this bloatware.

Something I thought of for the profile is [this design](https://a.pomf.cat/oryigz.png) which I like very much from Google+. Notice the header is repeated with frosted glass effect underneath the profile.
Here's how I would adapt it from the Google+ version with an ugly mspaint graph (for some reason my Inspect element button doesn't work and I'm too lazy to make a mockup.)

![profile with indicators](https://a.pomf.cat/uonpmb.png)
1. Display name (obviously)
2. Username/ @name (do we put it underneath or next to the display name, with a muted color and smaller font? I like the second one better). Verified/translator badge should be put there.
3. Bio, this one is obvious as well.
4. Website. (75% opacity unless hovered)
5. Location. (75% opacity unless hovered)
6. Number of tweets (ex: 75k, displays the exact amount like 75,258 when hovered)
7. Number of followed users. (works the same as the number of tweets)
8. Number of followers. (ditto)
9. Number of favorited tweets. (again)
10. Avatars of users you know following this user. (TweetDeck has the same feature) Hovering one avatar displays a pop-out tag (I figure something like a frosted glass pane with a darker shade) that displays the @name of the user.
11. Follow/unfollow/edit profile button. This one should have a [big coloured (the colour of the user's profile, perhaps? I don't know if it's easy to get it from Twitter, but I do recall that Twidere and a few others are able to)/black background and a thick font](http://materializecss.com/buttons.html#raised). Or maybe a [FAB](http://materializecss.com/buttons.html#floating) would work.
12. [Profile actions](https://a.pomf.cat/xtummw.png). I see this one almost certainly being a click-only horizontal FAB, but the issue with this is that you can't have two FABs on a same object according to Material guidelines, and the FAB should always be the most important action, thereby disqualifying the 11th item, follow button, from being a second FAB, and the Follow button being the most important action disqualifying the 12th item from being a FAB as well.
    I totally forgot the "FOLLOWS YOU" display but you can put it pretty much anywhere really.

This design would put the accent on user expression. It doesn't need to take half the space of the screen, but the way TweetDeck handles profiles is ridiculous. [It's way too small and feels cramped](https://a.pomf.cat/gptvfp.png) yet it still fades out the background, meaning that it prioritizes the task over what's in the background. Then, make it so that it _does_ look important. What better way than let users display their fancy header and avatar in a proper resolution? Perhaps you could handle it in a way that [it's a slide-in from the left like ModernDeck](https://a.pomf.cat/rcafwr.png) but with more emphasis of how important it is and much bigger, along with their latest tweets underneath, like a legitimate Twitter profile. That way, you would look at someone's profile and still have one or two columns in the background; since most people's leftmost column is their timeline.

That should be about it on my ideas about the profile, I'll try and do another post when I have a few more ideas.

**Comment by pixeldesu** [comment]
> Hey! You know I would get involved, didn't you?

Of course I did know that :P 

> I would focus design on removing the most bloat possible.

Code-wise, I already removed most bloat with revising TweetDeck's HTML/CSS and removing helper classes and only using 1-3 CSS classes on an object.

> Something like a "mobile" theme [...]

I plan to do something like this with moving the compose drawer to the bottom if the window width is small enough, so you can just view like...1 column but also use the fixed compose-drawer at the bottom.

> Something you can try is a very Material theme like ModernDeck [...]

I personally think that Material Design belongs more to the mobile-market, it has nice guidelines but these are not properly suited for web applications, considering they waste a lot of space because of the direct (touch) interaction based contexts.

> Perhaps looking into Materialize.css and the Material guidelines would be a good thing to start.

Already tried this, Materialize does not work with my software stack, because of requiring modules at wrong places that is unfixable for me.

> An iOS theme, maybe?

Maybe. Yet it wouldn't really be iOS/Mac-ish, but really inspired off the guidelines. I might replace the iconset with something else, considering the fact that FontAwesome icons are really unproportional and that makes the actions look weird inside tweets.

---

Your profile ideas are already really specific, this issue is mostly about a general styling and specific parts can be discussed later on, yet I like the idea and points you make with this one.

The ability of using [CSS backdrop filters](https://developer.mozilla.org/en-US/docs/Web/CSS/backdrop-filter) also makes the frosted glass effect quite easy to accomplish.

---

I started with making the entire app platform agnostic, speaking it now uses the preferred system fonts (Helvetica Neue, etc. pp. on Mac OS X, Segoe UI for Windows, Ubuntu for...Ubuntu, etc. etc.)

I also winded down the scrollbars to the small kind-of OS X look.

**Comment by tmprnc** [comment]
> not properly suited for web applications

I would tend to disagree, but it's just a matter of opinion I guess.
I mean;

> they waste a lot of space because of the direct (touch) interaction based contexts.

They can somewhat be adapted, and the very idea of flat design is so that there's less "bloat" on the screen. You can still make UI elements smaller &/or slightly more cramped maybe.

> Maybe. Yet it wouldn't really be iOS/Mac-ish, but really inspired off the guidelines. I might replace the iconset with something else, considering the fact that FontAwesome icons are really unproportional and that makes the actions look weird inside tweets.

Well, I sure am glad to hear that. A custom SVG font maybe?

> Your profile ideas are already really specific, this issue is mostly about a general styling and specific parts can be discussed later on, yet I like the idea and points you make with this one.

B-b-but I thought we were talking about the default skins!
Yes, it is really specific, it was one of my suggestions for the default theme(s), of course I expect custom themes to maybe work differently. Regardless, I expect users to base themselves on the default themes as a guideline when making a custom one so I suppose each of these themes are going to have to be coherent and consistent in their own way.

> the preferred system fonts (Helvetica Neue, etc. pp. on Mac OS X, Segoe UI for Windows, Ubuntu for...Ubuntu, etc. etc.)

Luckily this can be changed manually. Nothing against you; Helvetica Neue is a good font family but Segoe UI has the problem that it's good mostly for displaying big texts (read: at least 20px) but it looks kinda out of place in smaller scales, when Calibri/ Calibri Light does a better job. As for Ubuntu, I've never liked this font. If anything, the only libre font I could ever look at as a proper UI font (or even a proper font at all) is Noto Sans. One of the best UI fonts in my opinion is still Roboto/ RobotoDraft which can obviously be accessed very simply thanks to Google's Fonts API.

> I also winded down the scrollbars to the small kind-of OS X look.

Perfect. The huge-ass bloat that is the scrollbar is one of the worst problems of Windows and the one thing I can't ever stand when using TweetDeck without snwflk.

**Comment by NickVst** [comment]
Another suggestion would be to "_streamline_" the user interface. 
For example, opening the Settings menu, changing settings and clicking on Save could close the Settings dialog. This reduces the overall amount of clicks made by the user.

Saving settings could be accompanied by a notification that tells the user that the change took place, e.g. "Changed the settings successfully" (although, does clicking 'save settings' actually do anything currently?). It could either use a desktop notification in the way that one is used whenever an interaction happens, or a small message could pop up in the bottom right corner.

**Comment by pixeldesu** [comment]
> For example, opening the Settings menu, changing settings and clicking on Save could close the Settings dialog.

I'm probably just going to remove that, as settings get applied instantly.

> [...] or a small message could pop up in the bottom right corner.

I will do that for the most things, as sending tweets, favoriting, retweeting etc. pp. and also for errors occuring, I just need to find a good library for JS toasts.
